#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Customize to your needs...
# Configuracion POWERLVEL9K
export TERM="xterm-256color"
POWERLEVEL9K_MODE='nerdfont-complete'
#NUEVA LINEA
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='\uf0da'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir dir_writable vcs dropbox)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status ip ssh)
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0b0'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0b2'
# AÑADIR CONTEXT EN LEFT_PROMPT_ELEMENTS POWERLEVEL9K_CONTEXT_TEMPLATE='%n'
#POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='springgreen3'
#POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='black'

#COLORES Y FORMA DE MOSTRAR RUTAS
POWERLEVEL9K_SHORTEN_STRATEGY='truncate_middle'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_DIR_HOME_BACKGROUND='deepskyblue2'
POWERLEVEL9K_DIR_HOME_FOREGROUND='black'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='deepskyblue2'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='black'

#COLORES INDICADOR SO
POWERLEVEL9K_OS_ICON_BACKGROUND='white'
POWERLEVEL9K_OS_ICON_FOREGROUND='deepskyblue3'
#'#31363B FONDO ICONO GRIS

#COLORES GIT
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='green'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='grey11'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='grey11'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='red'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='grey11'

#COLORES SALIDA STATUS
POWERLEVEL9K_STATUS_OK_BACKGROUND='white'
POWERLEVEL9K_STATUS_OK_FOREGROUND='green'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='white'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='red'

#COLORES INDICADOR IP DE RED
POWERLEVEL9K_IP_BACKGROUND='plum4'
POWERLEVEL9K_IP_FOREGROUND='white'


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


